export const ADD_NEW_FLASH_MESSAGE = "ADD_NEW_FLASH_MESSAGE";
export const DELETE_FLASH_MESSAGE = "DELETE_FLASH_MESSAGE";
export const SET_AUTHORIZATION = "SET_AUTHORIZATION";
export const USER_LOGOUT = "USER_LOGOUT";
